// <auto-generated />
using System;
using BinderDyn.OrchardCore.EventSourcing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinderDyn.OrchardCore.EventSourcing.Migrations
{
    [DbContext(typeof(EventSourcingDbContext))]
    [Migration("20230725180243_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventState")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeFriendlyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalEventEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("OriginalEventEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Models.Event", b =>
                {
                    b.HasOne("BinderDyn.OrchardCore.EventSourcing.Models.Event", "OriginalEvent")
                        .WithMany()
                        .HasForeignKey("OriginalEventEventId");

                    b.Navigation("OriginalEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
