// <auto-generated />
using System;
using BinderDyn.OrchardCore.EventSourcing.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinderDyn.OrchardCore.EventSourcing.Postgres.Migrations
{
    [DbContext(typeof(EventSourcingPostgresDbContext))]
    [Migration("20230914094334_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventState")
                        .HasColumnType("integer");

                    b.Property<string>("EventTypeFriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalEventEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("OriginalEventEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", b =>
                {
                    b.HasOne("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", "OriginalEvent")
                        .WithMany()
                        .HasForeignKey("OriginalEventEventId");

                    b.Navigation("OriginalEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
