// <auto-generated />
using System;
using BinderDyn.OrchardCore.EventSourcing.MySql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinderDyn.OrchardCore.EventSourcing.MySql.Migrations
{
    [DbContext(typeof(EventSourcingMySqlDbContext))]
    [Migration("20230914115706_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventState")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeFriendlyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OriginalEventEventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.HasKey("EventId");

                    b.HasIndex("OriginalEventEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", b =>
                {
                    b.HasOne("BinderDyn.OrchardCore.EventSourcing.Abstractions.Models.Event", "OriginalEvent")
                        .WithMany()
                        .HasForeignKey("OriginalEventEventId");

                    b.Navigation("OriginalEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
